from datetime import datetime, timezone
from typing import Any, Optional

from sqlalchemy import DateTime, ForeignKey, Integer, JSON, String
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.enums import ETaxExportType, ValidationStatus


class ETaxExportLog(Base):
    """An audit trail of every BIR e-Tax file / PDF generated by the system.

    This backs the "e-Tax File Export Center" screen: the list of generated
    XML/CSV/PDF artifacts, their validation status, and a downloadable
    reference. The actual bytes are written to disk under
    settings.storage_dir/exports/ and referenced by `file_path`; only
    metadata + a content hash live in the DB.
    """

    __tablename__ = "etax_export_logs"

    id: Mapped[int] = mapped_column(primary_key=True)
    client_id: Mapped[int] = mapped_column(ForeignKey("clients.id"), nullable=False)
    generated_by_user_id: Mapped[Optional[int]] = mapped_column(ForeignKey("users.id"), nullable=True)

    export_type: Mapped[ETaxExportType] = mapped_column(
        SAEnum(ETaxExportType, native_enum=False, length=64), nullable=False
    )
    tax_year: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    file_name: Mapped[str] = mapped_column(String(255), nullable=False)
    file_path: Mapped[str] = mapped_column(String(500), nullable=False)
    content_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    row_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    validation_status: Mapped[ValidationStatus] = mapped_column(
        SAEnum(ValidationStatus, native_enum=False, length=32),
        default=ValidationStatus.PENDING,
        nullable=False,
    )
    validation_messages: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)

    # Free-form snapshot of whatever source record(s) produced this export
    # (e.g. {"individual_return_id": 12} or {"td4_input_ids": [1,2,3]}).
    source_reference: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=False, default=dict)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))

    client: Mapped["Client"] = relationship()
