"""e-Tax File Export Center endpoints.

Every export writes an ETaxExportLog row (the audit trail / validation
status list the Export Center UI displays) and the generated bytes to
storage/exports/{client_id}/, then streams the file back to the caller.
"""
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.orm import Session

from app.database import get_db
from app.dependencies import get_accessible_client, get_current_user
from app.models.enums import ETaxExportType, ValidationStatus
from app.models.etax_export import ETaxExportLog
from app.models.returns import CorporateReturn, IndividualReturn, VAT200Return
from app.models.td4 import TD4Input
from app.models.user import User
from app.models.payroll import PayrollRun
from app.schemas import (
    ETaxExportLogOut,
    NonLoggedInReturnExportRequest,
    TD4CsvExportRequest,
    VAT200ExportRequest,
)
from app.services import etax_export, pdf_service
from app.services.entitlements import get_tier_limits
from app.services.etax_export import GeneratedFile, save_export_file

router = APIRouter(prefix="/etax-export", tags=["etax-export"])


def _require_etax_export_entitlement(current_user: User) -> None:
    """Free tier gets on-screen previews only; unlocking BIR e-Tax upload
    file generation requires a paid upgrade, per the monetization matrix."""
    if not get_tier_limits(current_user.subscription_tier).can_export_etax_files:
        raise HTTPException(
            status_code=402,
            detail="e-Tax file export requires a Pro plan or higher. Upgrade your subscription to unlock this feature.",
        )


def _require_official_pdf_entitlement(current_user: User) -> None:
    if not get_tier_limits(current_user.subscription_tier).can_generate_official_pdfs:
        raise HTTPException(
            status_code=402,
            detail="Downloading official PDF returns requires a Pro plan or higher. Upgrade your subscription to unlock this feature.",
        )


def _log_export(db: Session, client_id: int, user_id: int, export_type: ETaxExportType, generated: GeneratedFile, tax_year: int | None, source_reference: dict) -> ETaxExportLog:
    path = save_export_file(client_id, generated)
    log = ETaxExportLog(
        client_id=client_id,
        generated_by_user_id=user_id,
        export_type=export_type,
        tax_year=tax_year,
        file_name=generated.file_name,
        file_path=str(path),
        content_sha256=etax_export.content_hash(generated.content_bytes),
        row_count=generated.row_count,
        validation_status=generated.validation_status,
        validation_messages=generated.validation_messages,
        source_reference=source_reference,
    )
    db.add(log)
    db.commit()
    db.refresh(log)
    return log


def _content_type_for(file_name: str) -> str:
    if file_name.endswith(".csv"):
        return "text/csv"
    if file_name.endswith(".xml"):
        return "application/xml"
    if file_name.endswith(".json"):
        return "application/json"
    if file_name.endswith(".pdf"):
        return "application/pdf"
    return "application/octet-stream"


@router.get("/logs", response_model=list[ETaxExportLogOut])
def list_export_logs(client_id: int, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    get_accessible_client(client_id, db, current_user)
    logs = db.query(ETaxExportLog).filter(ETaxExportLog.client_id == client_id).order_by(ETaxExportLog.created_at.desc()).all()
    return [
        ETaxExportLogOut(
            id=log.id,
            client_id=log.client_id,
            export_type=log.export_type,
            tax_year=log.tax_year,
            file_name=log.file_name,
            row_count=log.row_count,
            validation_status=log.validation_status,
            validation_messages=log.validation_messages,
            created_at=log.created_at.isoformat(),
        )
        for log in logs
    ]


@router.post("/td4-supplementary-csv")
def export_td4_supplementary_csv(
    payload: TD4CsvExportRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    get_accessible_client(payload.client_id, db, current_user)
    _require_etax_export_entitlement(current_user)

    query = db.query(TD4Input).filter(
        TD4Input.client_id == payload.client_id, TD4Input.income_year == payload.income_year
    )
    if payload.td4_input_ids:
        query = query.filter(TD4Input.id.in_(payload.td4_input_ids))
    td4_inputs = query.all()

    generated = etax_export.generate_td4_supplementary_csv(td4_inputs, payload.income_year)
    log = _log_export(
        db,
        payload.client_id,
        current_user.id,
        ETaxExportType.TD4_SUPPLEMENTARY_CSV,
        generated,
        payload.income_year,
        {"td4_input_ids": [t.id for t in td4_inputs]},
    )

    return Response(
        content=generated.content_bytes,
        media_type="text/csv",
        headers={
            "Content-Disposition": f'attachment; filename="{generated.file_name}"',
            "X-Export-Log-Id": str(log.id),
            "X-Validation-Status": generated.validation_status.value,
        },
    )


@router.post("/vat200-upload-csv")
def export_vat200_upload_csv(
    payload: VAT200ExportRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    vat_return = db.get(VAT200Return, payload.vat200_return_id)
    if not vat_return:
        raise HTTPException(status_code=404, detail="VAT200 return not found")
    client = get_accessible_client(vat_return.client_id, db, current_user)
    _require_etax_export_entitlement(current_user)

    generated = etax_export.generate_vat200_upload_csv(
        client.bir_number or "", client.tin or "", vat_return.computed | {
            "period_start": vat_return.period_start,
            "period_end": vat_return.period_end,
        }
    )
    log = _log_export(
        db,
        client.id,
        current_user.id,
        ETaxExportType.VAT200_UPLOAD_CSV,
        generated,
        int(vat_return.period_start[:4]),
        {"vat200_return_id": vat_return.id},
    )

    return Response(
        content=generated.content_bytes,
        media_type="text/csv",
        headers={
            "Content-Disposition": f'attachment; filename="{generated.file_name}"',
            "X-Export-Log-Id": str(log.id),
            "X-Validation-Status": generated.validation_status.value,
        },
    )


def _load_return_and_client(db: Session, current_user: User, return_type: str, return_id: int):
    model = IndividualReturn if return_type == "individual_return" else CorporateReturn
    tax_return = db.get(model, return_id)
    if not tax_return:
        raise HTTPException(status_code=404, detail="Return not found")
    client = get_accessible_client(tax_return.client_id, db, current_user)
    return tax_return, client


@router.post("/non-logged-in-return")
def export_non_logged_in_return(
    payload: NonLoggedInReturnExportRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    tax_return, client = _load_return_and_client(db, current_user, payload.return_type, payload.return_id)
    _require_etax_export_entitlement(current_user)

    client_dict = {
        "bir_number": client.bir_number,
        "tin": client.tin,
        "display_name": client.display_name,
        "address": client.address,
    }

    if payload.format == "xml":
        generated = etax_export.generate_non_logged_in_return_xml(
            payload.return_type, tax_return.tax_year, client_dict, tax_return.computed
        )
        export_type = ETaxExportType.NON_LOGGED_IN_RETURN_XML
    else:
        generated = etax_export.generate_non_logged_in_return_json(
            payload.return_type, tax_return.tax_year, client_dict, tax_return.computed
        )
        export_type = ETaxExportType.NON_LOGGED_IN_RETURN_JSON

    log = _log_export(
        db, client.id, current_user.id, export_type, generated, tax_return.tax_year,
        {f"{payload.return_type}_id": tax_return.id},
    )

    return Response(
        content=generated.content_bytes,
        media_type=_content_type_for(generated.file_name),
        headers={
            "Content-Disposition": f'attachment; filename="{generated.file_name}"',
            "X-Export-Log-Id": str(log.id),
            "X-Validation-Status": generated.validation_status.value,
        },
    )


# --- PDF downloads (also logged, for the Export Center's "downloadable
# official PDF return copies" list) ---


@router.get("/pdf/form-440/{return_id}")
def download_form_440_pdf(return_id: int, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    tax_return = db.get(IndividualReturn, return_id)
    if not tax_return:
        raise HTTPException(status_code=404, detail="Return not found")
    client = get_accessible_client(tax_return.client_id, db, current_user)
    _require_official_pdf_entitlement(current_user)

    content = pdf_service.generate_form_440_pdf(
        {"display_name": client.display_name, "bir_number": client.bir_number}, tax_return.tax_year, tax_return.computed
    )
    generated = GeneratedFile(
        file_name=f"Form440_{client.display_name.replace(' ', '_')}_{tax_return.tax_year}.pdf",
        content_bytes=content,
        row_count=1,
        validation_status=ValidationStatus.PASSED,
        validation_messages=["TaxTrin-branded summary PDF (see NOTES.md for scope: not an official BIR form overlay)."],
    )
    _log_export(db, client.id, current_user.id, ETaxExportType.FORM_440_PDF, generated, tax_return.tax_year, {"individual_return_id": tax_return.id})

    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{generated.file_name}"'},
    )


@router.get("/pdf/form-500/{return_id}")
def download_form_500_pdf(return_id: int, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    tax_return = db.get(CorporateReturn, return_id)
    if not tax_return:
        raise HTTPException(status_code=404, detail="Return not found")
    client = get_accessible_client(tax_return.client_id, db, current_user)
    _require_official_pdf_entitlement(current_user)

    content = pdf_service.generate_form_500_pdf(
        {"display_name": client.display_name, "bir_number": client.bir_number}, tax_return.tax_year, tax_return.computed
    )
    generated = GeneratedFile(
        file_name=f"Form500_{client.display_name.replace(' ', '_')}_{tax_return.tax_year}.pdf",
        content_bytes=content,
        row_count=1,
        validation_status=ValidationStatus.PASSED,
        validation_messages=["TaxTrin-branded summary PDF (see NOTES.md for scope: not an official BIR form overlay)."],
    )
    _log_export(db, client.id, current_user.id, ETaxExportType.FORM_500_PDF, generated, tax_return.tax_year, {"corporate_return_id": tax_return.id})

    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{generated.file_name}"'},
    )


@router.get("/pdf/vat200/{return_id}")
def download_vat200_pdf(return_id: int, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    vat_return = db.get(VAT200Return, return_id)
    if not vat_return:
        raise HTTPException(status_code=404, detail="Return not found")
    client = get_accessible_client(vat_return.client_id, db, current_user)
    _require_official_pdf_entitlement(current_user)

    content = pdf_service.generate_vat200_pdf(
        {"display_name": client.display_name, "bir_number": client.bir_number},
        vat_return.period_start,
        vat_return.period_end,
        vat_return.computed,
    )
    generated = GeneratedFile(
        file_name=f"VAT200_{client.display_name.replace(' ', '_')}_{vat_return.period_start}.pdf",
        content_bytes=content,
        row_count=1,
        validation_status=ValidationStatus.PASSED,
        validation_messages=["TaxTrin-branded summary PDF (see NOTES.md for scope: not an official BIR form overlay)."],
    )
    _log_export(db, client.id, current_user.id, ETaxExportType.VAT200_PDF, generated, int(vat_return.period_start[:4]), {"vat200_return_id": vat_return.id})

    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{generated.file_name}"'},
    )


@router.get("/pdf/payment-voucher/{client_id}")
def download_payment_voucher_pdf(
    client_id: int,
    payment_type: str = "Quarterly Estimated Tax Payment",
    quarter_label: str = "",
    tax_year: int = 0,
    due_date: str = "",
    amount: float = 0,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Auto-populate a printable BIR payment voucher.

    Query-string driven rather than a full return lookup: quarterly
    estimated tax / statutory levy vouchers are frequently a standalone
    "I know the amount, print me a slip" action rather than something tied
    to a stored return.
    """
    client = get_accessible_client(client_id, db, current_user)
    voucher = {
        "payment_type": payment_type,
        "quarter_label": quarter_label,
        "tax_year": tax_year,
        "due_date": due_date,
        "amount": amount,
        "bir_account_reference": f"{(client.bir_number or '0000000000').zfill(10)}-{tax_year}-{quarter_label or 'NA'}",
    }
    content = pdf_service.generate_payment_voucher_pdf(
        {"display_name": client.display_name, "bir_number": client.bir_number}, voucher
    )
    generated = GeneratedFile(
        file_name=f"PaymentVoucher_{client.display_name.replace(' ', '_')}_{tax_year}_{quarter_label or 'NA'}.pdf",
        content_bytes=content,
        row_count=1,
        validation_status=ValidationStatus.PASSED,
        validation_messages=["TaxTrin-branded payment voucher summary (see NOTES.md for scope)."],
    )
    _log_export(db, client.id, current_user.id, ETaxExportType.PAYMENT_VOUCHER_PDF, generated, tax_year or None, {"voucher": voucher})

    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{generated.file_name}"'},
    )


@router.get("/pdf/payroll-summary/{run_id}")
def download_payroll_summary_pdf(run_id: int, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    run = db.get(PayrollRun, run_id)
    if not run:
        raise HTTPException(status_code=404, detail="Payroll run not found")
    client = get_accessible_client(run.client_id, db, current_user)

    lines = [
        {
            "employee_name": line.employee_name,
            "gross_pay": float(line.gross_pay),
            "nis_employee": float(line.nis_employee),
            "nis_employer": float(line.nis_employer),
            "health_surcharge_employee": float(line.health_surcharge_employee),
            "health_surcharge_employer": float(line.health_surcharge_employer),
            "paye_deducted": float(line.paye_deducted),
            "net_pay": float(line.net_pay),
        }
        for line in run.lines
    ]
    period_label = f"{run.pay_period_start} to {run.pay_period_end}"
    content = pdf_service.generate_payroll_summary_pdf({"display_name": client.display_name}, period_label, lines)

    generated = GeneratedFile(
        file_name=f"PayrollSummary_{client.display_name.replace(' ', '_')}_{run.pay_period_start}.pdf",
        content_bytes=content,
        row_count=len(lines),
        validation_status=ValidationStatus.PASSED,
        validation_messages=["TaxTrin-branded payroll summary PDF (see NOTES.md for scope)."],
    )
    _log_export(db, client.id, current_user.id, ETaxExportType.PAYROLL_SUMMARY_PDF, generated, int(run.pay_period_start[:4]), {"payroll_run_id": run.id})

    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{generated.file_name}"'},
    )
