"""Printable PDF generation: BIR form summaries, schedules, and vouchers.

IMPORTANT SCOPE NOTE: these are TaxTrin-branded SUMMARY documents that report
the same figures a Form 440 / Form 500 / VAT 200 would contain, in a clean
layout suitable for the taxpayer's own records or for attaching to a
manually-filed paper/e-Tax return. They are NOT pixel-accurate overlays onto
the BIR's actual form artwork (that would require the BIR's own form PDFs as
a base template, which are not bundled with this POC -- see NOTES.md). Where
the spec calls this "print-ready PDF returns matching the layout... of the
official BIR 440 form", read that as the target for a follow-on iteration
once the actual form templates are obtained from IRD; this POC produces the
correct figures in a well-organized, professional document instead.
"""
from datetime import datetime, timezone
from decimal import Decimal
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

_styles = getSampleStyleSheet()
_TITLE = ParagraphStyle("TaxTrinTitle", parent=_styles["Title"], fontSize=16, spaceAfter=4)
_SUBTITLE = ParagraphStyle("TaxTrinSubtitle", parent=_styles["Normal"], fontSize=10, textColor=colors.grey, spaceAfter=12)
_SECTION = ParagraphStyle("TaxTrinSection", parent=_styles["Heading2"], fontSize=12, spaceBefore=14, spaceAfter=6)
_BODY = _styles["Normal"]
_NOTE = ParagraphStyle("TaxTrinNote", parent=_styles["Normal"], fontSize=8, textColor=colors.grey, spaceBefore=10)

_TABLE_STYLE = TableStyle(
    [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
)


def _money(value) -> str:
    try:
        return f"${Decimal(str(value or 0)):,.2f}"
    except Exception:
        return "$0.00"


def _header(title: str, subtitle_lines: list[str]) -> list:
    elements = [Paragraph(title, _TITLE)]
    for line in subtitle_lines:
        elements.append(Paragraph(line, _SUBTITLE))
    return elements


def _kv_table(rows: list[tuple[str, str]], col_widths=(3.5 * inch, 2.5 * inch)) -> Table:
    table = Table(rows, colWidths=list(col_widths))
    table.setStyle(_TABLE_STYLE)
    return table


def _generated_footer() -> Paragraph:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return Paragraph(
        f"Generated by TaxTrin (POC) on {stamp}. This is a TaxTrin-branded summary of the return's "
        "computed figures for the taxpayer's records; it is not an official Board of Inland Revenue "
        "form artwork. Verify all figures before filing.",
        _NOTE,
    )


def _render(elements: list) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    elements.append(_generated_footer())
    doc.build(elements)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# Form 440 - Individual Income Tax Return summary
# ---------------------------------------------------------------------------


def generate_form_440_pdf(client: dict, tax_year: int, computed: dict) -> bytes:
    elements = _header(
        "Form 440 - Individual Income Tax Return (Summary)",
        [
            f"Tax Year {tax_year} &nbsp;|&nbsp; BIR File No. {client.get('bir_number', 'N/A')}",
            f"{client.get('display_name', '')}",
        ],
    )

    elements.append(Paragraph("Income & Chargeable Income", _SECTION))
    paye = computed.get("paye", {})
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Total income", _money(computed.get("total_income"))),
                ("Personal allowance", _money(paye.get("personal_allowance"))),
                ("NIS deductible portion (70%)", _money(paye.get("nis_deductible_portion"))),
                ("Other approved deductions", _money(paye.get("other_deductions"))),
                ("Chargeable income", _money(paye.get("chargeable_income"))),
            ]
        )
    )

    elements.append(Paragraph("Tax Computation", _SECTION))
    band_rows = [("Band", "Rate", "Taxable amount", "Tax")]
    for band in paye.get("tax_by_band", []):
        band_to = "above" if band["to"] is None else f"${band['to']:,.2f}"
        band_rows.append(
            (
                f"${band['from']:,.2f} - {band_to}",
                f"{band['rate'] * 100:.0f}%",
                _money(band["taxable_amount"]),
                _money(band["tax"]),
            )
        )
    band_table = Table(band_rows, colWidths=[2.2 * inch, 0.8 * inch, 1.5 * inch, 1.5 * inch])
    band_table.setStyle(_TABLE_STYLE)
    elements.append(band_table)

    elements.append(Paragraph("Levies & Balance", _SECTION))
    levies = computed.get("levies", {})
    balance_label = "Refund due to taxpayer" if computed.get("is_refund") else "Balance due to BIR"
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Total PAYE tax", _money(paye.get("total_tax"))),
                ("Business Levy payable", _money(levies.get("business_levy_payable"))),
                ("Total tax liability", _money(computed.get("total_tax_liability"))),
                ("PAYE already deducted (per TD4)", _money(computed.get("paye_already_deducted"))),
                (balance_label, _money(abs(computed.get("refund_or_balance_due", 0)))),
            ]
        )
    )

    if computed.get("deduction_notes"):
        elements.append(Paragraph("Notes on Deduction Caps Applied", _SECTION))
        for note in computed["deduction_notes"]:
            elements.append(Paragraph(f"&bull; {note}", _BODY))

    return _render(elements)


# ---------------------------------------------------------------------------
# Form 500 - Corporation Tax Return summary
# ---------------------------------------------------------------------------


def generate_form_500_pdf(client: dict, tax_year: int, computed: dict) -> bytes:
    elements = _header(
        "Form 500 - Corporation Tax Return (Summary)",
        [
            f"Accounting Year {tax_year} &nbsp;|&nbsp; BIR File No. {client.get('bir_number', 'N/A')}",
            f"{client.get('display_name', '')}",
        ],
    )

    elements.append(Paragraph("Corporation Tax", _SECTION))
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Chargeable profits", _money(computed.get("chargeable_profits"))),
                ("Rate applied", f"{float(computed.get('rate_applied', 0)) * 100:.1f}%"),
                ("Corporation tax", _money(computed.get("corporation_tax"))),
            ]
        )
    )

    elements.append(Paragraph("Statutory Levies", _SECTION))
    levies = computed.get("business_levy", {})
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Business Levy (gross, before offset)", _money(levies.get("business_levy_gross"))),
                ("Business Levy payable", _money(levies.get("business_levy_payable"))),
                ("Green Fund Levy", _money(levies.get("green_fund_levy"))),
            ]
        )
    )

    elements.append(Paragraph("Dividends & Balance", _SECTION))
    balance_label = "Refund due to company" if computed.get("is_refund") else "Balance due to BIR"
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Dividends paid", _money(computed.get("dividend_paid"))),
                (
                    f"Dividend withholding tax ({float(computed.get('dividend_withholding_tax_rate', 0)) * 100:.0f}%)",
                    _money(computed.get("dividend_withholding_tax")),
                ),
                ("Total statutory liability", _money(computed.get("total_statutory_liability"))),
                ("Quarterly instalments already paid", _money(computed.get("quarterly_installments_paid"))),
                (balance_label, _money(abs(computed.get("refund_or_balance_due", 0)))),
            ]
        )
    )

    return _render(elements)


# ---------------------------------------------------------------------------
# VAT 200 summary
# ---------------------------------------------------------------------------


def generate_vat200_pdf(client: dict, period_start: str, period_end: str, computed: dict) -> bytes:
    elements = _header(
        "Form VAT 200 - Value Added Tax Return (Summary)",
        [
            f"Period {period_start} to {period_end}",
            f"{client.get('display_name', '')} &nbsp;|&nbsp; BIR File No. {client.get('bir_number', 'N/A')}",
        ],
    )

    elements.append(Paragraph("Sales", _SECTION))
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Standard-rated sales", _money(computed.get("standard_rated_sales"))),
                ("Zero-rated sales", _money(computed.get("zero_rated_sales"))),
                ("Exempt sales", _money(computed.get("exempt_sales"))),
            ]
        )
    )

    elements.append(Paragraph("VAT Computation", _SECTION))
    balance_label = "VAT refund due" if computed.get("is_refund") else "Net VAT payable"
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Output VAT", _money(computed.get("output_vat"))),
                ("Input VAT", _money(computed.get("input_vat"))),
                (balance_label, _money(abs(computed.get("net_vat_payable", 0)))),
            ]
        )
    )

    return _render(elements)


# ---------------------------------------------------------------------------
# BIR Payment Voucher (quarterly estimated tax / statutory levies)
# ---------------------------------------------------------------------------


def generate_payment_voucher_pdf(client: dict, voucher: dict) -> bytes:
    """`voucher` keys: payment_type, tax_year, quarter_label, due_date, amount,
    bir_account_reference."""
    elements = _header(
        "BIR Payment Voucher (Summary)",
        [
            f"{voucher.get('payment_type', 'Estimated Tax Payment')} &nbsp;|&nbsp; {voucher.get('quarter_label', '')}",
        ],
    )
    elements.append(
        _kv_table(
            [
                ("Description", "Detail"),
                ("Taxpayer", client.get("display_name", "")),
                ("BIR File No.", client.get("bir_number", "N/A")),
                ("BIR Account Reference", voucher.get("bir_account_reference", "N/A")),
                ("Tax Year", str(voucher.get("tax_year", ""))),
                ("Due Date", voucher.get("due_date", "")),
                ("Amount Payable", _money(voucher.get("amount"))),
            ]
        )
    )
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(
        Paragraph(
            "Detach and present this voucher with payment at any Inland Revenue Division office, "
            "or quote the BIR Account Reference above when paying via e-Tax / linkt2pay.",
            _BODY,
        )
    )
    return _render(elements)


# ---------------------------------------------------------------------------
# Monthly PAYE / NIS / Health Surcharge payroll summary
# ---------------------------------------------------------------------------


def generate_payroll_summary_pdf(employer: dict, period_label: str, lines: list[dict]) -> bytes:
    elements = _header(
        "PAYE / NIS / Health Surcharge - Monthly Summary",
        [f"{employer.get('display_name', '')} &nbsp;|&nbsp; Period: {period_label}"],
    )

    rows = [("Employee", "Gross Pay", "NIS (Ee/Er)", "Health Surch. (Ee/Er)", "PAYE", "Net Pay")]
    totals = {"gross": Decimal("0"), "nis_ee": Decimal("0"), "nis_er": Decimal("0"), "hs_ee": Decimal("0"), "hs_er": Decimal("0"), "paye": Decimal("0"), "net": Decimal("0")}

    for line in lines:
        gross = Decimal(str(line.get("gross_pay", 0)))
        nis_ee = Decimal(str(line.get("nis_employee", 0)))
        nis_er = Decimal(str(line.get("nis_employer", 0)))
        hs_ee = Decimal(str(line.get("health_surcharge_employee", 0)))
        hs_er = Decimal(str(line.get("health_surcharge_employer", 0)))
        paye = Decimal(str(line.get("paye_deducted", 0)))
        net = Decimal(str(line.get("net_pay", 0)))

        rows.append(
            (
                line.get("employee_name", ""),
                _money(gross),
                f"{_money(nis_ee)} / {_money(nis_er)}",
                f"{_money(hs_ee)} / {_money(hs_er)}",
                _money(paye),
                _money(net),
            )
        )
        totals["gross"] += gross
        totals["nis_ee"] += nis_ee
        totals["nis_er"] += nis_er
        totals["hs_ee"] += hs_ee
        totals["hs_er"] += hs_er
        totals["paye"] += paye
        totals["net"] += net

    rows.append(
        (
            "TOTAL",
            _money(totals["gross"]),
            f"{_money(totals['nis_ee'])} / {_money(totals['nis_er'])}",
            f"{_money(totals['hs_ee'])} / {_money(totals['hs_er'])}",
            _money(totals["paye"]),
            _money(totals["net"]),
        )
    )

    table = Table(rows, colWidths=[1.6 * inch, 0.9 * inch, 1.3 * inch, 1.3 * inch, 0.8 * inch, 0.9 * inch])
    style = TableStyle(_TABLE_STYLE.getCommands())
    style.add("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold")
    style.add("LINEABOVE", (0, -1), (-1, -1), 1, colors.black)
    table.setStyle(style)
    elements.append(table)

    elements.append(Paragraph("Totals due for remittance to the Board of Inland Revenue / NIBTT:", _SECTION))
    elements.append(
        _kv_table(
            [
                ("Description", "Amount"),
                ("Total NIS (employee + employer)", _money(totals["nis_ee"] + totals["nis_er"])),
                ("Total Health Surcharge (employee + employer)", _money(totals["hs_ee"] + totals["hs_er"])),
                ("Total PAYE remitted", _money(totals["paye"])),
            ]
        )
    )

    return _render(elements)
